#include "xsplice.h"

#define NAME "xen_extra_version\0"

/* From version.o. */
extern char xen_extra_version[];
/* And this is generated by xsplice.lds. */
extern char _xen_extra_version_size[];

/* Computed by xsplice.lds. TODO: What is the SIZEOF 'size' ? 8 bytes? */
extern uint32_t _xsplice_relocs_size;
extern uint32_t _xsplice_patches_size;
extern uint32_t _xsplice_sections_size;

/* Extracted from the xen-syms. */
extern char __note_gnu_build_id_start[];
extern uint32_t xen_build_id_size;

struct xsplice_symbol xsplice_symbol_NAME = {
    .name = "xen_extra_version",
    .label = "xen_extra_version+<0x0>",
    .pad = { 'S' ,'Y', 'M', 'B', 'O', 'L', },
};

struct xsplice_reloc_howto xsplice_reloc_howto_NAME = {
    .howto = XSPLICE_HOWTO_RELOC_PATCH,
    .flag = XSPLICE_HOWTO_FLAG_PC_REL,
    .r_shift = 0,
    .mask = (-1ULL),
};


struct xsplice_reloc xsplice_relocs_NAME[1] = {
    {
        .addr = 0 /* XXX: To compute when generting payload. */,
        .symbol = &xsplice_symbol_NAME,
        .isns_target = 0,
        .howto = &xsplice_reloc_howto_NAME,
        .isns_added = -4,
        .pad = { 'R', 'E', 'L', 'O','C', },
    }
};



struct xsplice_section xsplice_sections_NAME[1] = {
    {
        .symbol = &xsplice_symbol_NAME,
        .address = 0 /* XXX: To compute when generting payload. If known. */,
        .flags = XSPLICE_SECTION_TEXT,
        .size = _xen_extra_version_size,
        .pad = { 'S', 'E', 'C', 'T', 'I', 'O', 'N', },
    }
};

struct xsplice_patch xsplice_patches_NAME[1] = {
    {
        .type = XSPLICE_PATCH_RELOC_TEXT,
        .addr = 0,
        .content = xen_extra_version,
        .size = _xen_extra_version_size,
        .pad = { 'P' ,'A','T','C','H', },
    }
};

struct xsplice_code xsplice_code_NAME = {
    .relocs = &xsplice_relocs_NAME[0],
    .relocs_len = &_xsplice_relocs_size,
    .sections = &xsplice_sections_NAME[0],
    .sections_len = &_xsplice_sections_size,
    .patches = &xsplice_patches_NAME[0],
    .patches_len = &_xsplice_patches_size,
    .pad = { 'C','O','D','E',  },
};

struct xsplice xsplice = {
    .name = NAME,
    .build_id = __note_gnu_build_id_start,
    .build_id_len = &xen_build_id_size,
    .old = 0,
    .new = &xsplice_code_NAME,
    .pad = { 'X', 'S', 'P', 'L', 'I', 'C' ,'E' }
};
